=== Nagarajan17699/EYIntern/Day14_Exercise/books.dtd
<!ELEMENT books (book+)>
<!ELEMENT book (id,name,author+,prize?,imported?)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT prize (#PCDATA)>
<!ELEMENT imported EMPTY>

=== Nagarajan17699/EYIntern/Day14_Exercise/books.xml
<!DOCTYPE books SYSTEM "books.dtd">
<books>
	<book>
		<id>100</id>
		<name>java</name>
		<author>james</author>
		<author>siera</author>
	</book>
	<book>
		<id>100</id>
		<name>xml</name>
		<author>jason</author>
		<prize>250</prize>
		<imported/>
	</book>
</books>
