=== Nagarajan17699/EYIntern/Day15/customer.dtd
<!ELEMENT customers (customer+)>
<!ELEMENT customer (name,email,phone,amount,date)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT amount (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== Nagarajan17699/EYIntern/Week3Projects/customer.xml
<!DOCTYPE customers SYSTEM "customer.dtd">
<customers>
    <customer>
        <name>Nagarajan S</name>
        <email>lasdnvion@sdfv.sdp</email>
        <phone>24534534654</phone>
        <amount>2334</amount>
        <date>23/3/21</date>
    </customer>
    
    <customer>
        <name>abc</name>
        <email>sfsgfsfsion@sdfv.sdp</email>
        <phone>7836378634654</phone>
        <amount>3634</amount>
        <date>24/3/21</date>
    </customer>
</customers>
